basePath: /v1
host: '{{.Host}}'
info:
  contact:
    email: support@swagger.io
    name: Araujo
  description: '{{.Description}}'
  license: {}
  title: currency.converter
  version: "1.0"
paths: {}
swagger: "2.0"
